Leonard
leonard-pak/technopark-qa-hw1 pull request #1
Opened 2023-02-28 11:33 UTC by MrLeonardPak

2023-03-03 11:01 UTC, themilchenko requested changes

2023-03-03 11:01 UTC, themilchenko commented on vdonate.md
> +> Реальность: Перенос строки
А почему это именно БАГ? Может же быть такое, что мы не ожидали описанного поведения на этот шорткат.

2023-03-03 11:01 UTC, themilchenko commented on vdonate.md
> +- Создание поста с картинки внутри текста ✅
"с картинки" -> "с картинкой/картинками"

2023-03-04 16:50 UTC, george007361 approved these changes

2023-03-04 18:07 UTC, zeronethunter approved these changes

2023-03-05 20:05 UTC, MrLeonardPak commented on vdonate.md
> +> Реальность: Перенос строки
Потому что в описании на Shift+Enter  работает сохранение. Поправил описание

2023-03-05 20:26 UTC, themilchenko approved these changes

2023-03-08 16:59 UTC, merged