Milchenko
leonard-pak/technopark-qa-hw1 pull request #2
Opened 2023-02-28 15:47 UTC by themilchenko

Functional tests for `likes`, `comments` and `author subscriptions`.

2023-03-01 19:04 UTC, MrLeonardPak requested changes

2023-03-01 19:04 UTC, leonard-pak commented on vdonate.md
> +## Тестирование комментариев к постам
Добавил бы ещё то, что верстка прыгает при нажатии на кнопку комментария

2023-03-01 19:04 UTC, MrLeonardPak commented on vdonate.md
> +> `NOTE`: Тестирование изменения и удаления авторской подписки было решено объединить, так как функционал изменения включает в себя функционал удааления подписки.
удааления

2023-03-01 19:04 UTC, MrLeonardPak commented on vdonate.md
> +1. При уже созданной подписки нажатие кнопки "Изменить" приводит к вылезанию модального окна с заполненными текущими формами и тремя кнопками снизу: "Изменить", "Отменить", "Удалить";
к вылезанию -> к появлению

2023-03-01 19:04 UTC, leonard-pak commented on vdonate.md
> +> `BUG`: В случае, когда донатер покупает подписку, а автор затем ее удаляет, человек лишается заплаченного контента и деньги обратно не вернутся.
Если это баг, то добавь ожидаемое поведение. А так похоже на фичу)

2023-03-01 19:07 UTC, MrLeonardPak commented on vdonate.md
> +1. Нажатие "плюса" около "Уровни подписок" приводит к вылезанию модального окна с пустыми формами для заполнения;
к вылезанию -> к появлению

2023-03-03 16:38 UTC, zeronethunter approved these changes

2023-03-04 16:50 UTC, george007361 approved these changes

2023-03-05 20:02 UTC, MrLeonardPak approved these changes

2023-03-08 17:05 UTC, merged