George
leonard-pak/technopark-qa-hw1 pull request #3
Opened 2023-02-28 19:24 UTC by george007361

Functional tests for profile page, search page and pop-up's.

2023-03-03 11:02 UTC, themilchenko approved these changes

2023-03-03 17:03 UTC, zeronethunter requested changes

2023-03-03 17:03 UTC, zeronethunter commented on vdonate.md
> +## Работа елементов меню
Элементов*

2023-03-03 17:03 UTC, zeronethunter commented on vdonate.md
> +- Левом меню активный пункт подсвечивается
В левом меню*

2023-03-03 17:03 UTC, zeronethunter commented on vdonate.md
> +## Страница поиска:
Попробуй еще ввести 'они'. При существующем пользователе 'Тони', поиск выведет, что ничего не найдено. Соответственно баг в полнотекстовом поиске 😄

2023-03-03 17:03 UTC, zeronethunter commented on vdonate.md
> +- В правом сайд-баре отображается аватарка, ник, количество донаретов, количество постов пользователя
донатеров*

2023-03-03 17:03 UTC, zeronethunter commented on vdonate.md
> +- Самбит пустого поля с email
Это не баг, просто можно отправлять на сервер пустые поля, они там не будут меняться с существующими. Такая логика)

2023-03-03 17:03 UTC, zeronethunter commented on vdonate.md
> +- Ввести очень длинный email (более 64 символов)
На самом деле, максимальная длина email - 255, можно считать, что это баг.

2023-03-03 17:03 UTC, zeronethunter commented on vdonate.md
> +- Самбит пустого поля
Писал выше ⬆️

2023-03-04 16:11 UTC, george007361 commented on vdonate.md
> +## Страница поиска:
Спасибо! Не обратил на это внимания)

2023-03-04 18:06 UTC, zeronethunter approved these changes

2023-03-05 20:10 UTC, MrLeonardPak approved these changes

2023-03-08 17:07 UTC, merged