Zenehu
leonard-pak/technopark-qa-hw1 pull request #4
Opened 2023-02-28 19:33 UTC by zeronethunter

2023-02-28 19:42 UTC, george007361 commented on vdonate.md
> +## 1. Оплата
Что если в процессе оплаты на странице с банком, обновить страницу с vdonate?

2023-03-01 21:28 UTC, george007361 requested changes
Проверить прошлое замечание

2023-03-02 04:51 UTC, zeronethunter commented on vdonate.md
> +## 1. Оплата
Невозможно открыть оплату подписки в новой вкладке, т.к. ссылка генерится непосредственно после нажатия на кнопку, а потом происходит редирект пользователя. Так что эта проверка невозможна)

2023-03-03 11:01 UTC, themilchenko approved these changes

2023-03-05 19:38 UTC, george007361 requested changes

2023-03-05 19:38 UTC, george007361 commented on vdonate.md
> +- Нажатие на кнопку оплата редиректит на сервис оплаты ✅
Стили:
Каждый пункт договорились нумеровать
ex: 
1. Нажатие на кнопку оплата редиректит на сервис оплаты ✅

2023-03-05 19:45 UTC, george007361 requested changes

2023-03-05 19:45 UTC, george007361 commented on vdonate.md
> +При желании подписаться на автора, нужно оплатить его подписку. Поэтому под оплатой подразувевается успешное пополнение баланса автора и приобретение желаемой подписки.
*Подразумевается

2023-03-05 19:45 UTC, george007361 commented on vdonate.md
> +- После перехода по ссылке пришется краткая информация о транзакции ✅
*Пишется

2023-03-05 19:45 UTC, george007361 commented on vdonate.md
> +- Вывод на существующий номер карты с нехваткой баланса для коммисии (50 рублей + 5%) ❌
*Комиссии

2023-03-05 20:21 UTC, george007361 requested changes

2023-03-05 20:21 UTC, george007361 commented on vdonate.md
> +- Проверяем транзакцию из секции [оплата](#1-оплата)
Мб лучше стоит написать как-то по типу ".... транзакцию из секции оплата на аккаунте автора" 

Не сразу догнал, что в этом блоке нужно чекать профиль автора

2023-03-05 20:21 UTC, george007361 commented on vdonate.md
> +- Пополнение баланса ✅
Я бы написал:  "Баланс в профиле автора увеличивается"

2023-03-05 20:21 UTC, george007361 commented on vdonate.md
> +- Только ввод цифр ✅
Судя по лекции, лучше все кейсы расписать.

ex: 
Ввод цифр доступен
Ввод букв недоступен
....

2023-03-05 20:21 UTC, george007361 commented on vdonate.md
> +- Некорректная длина номера телефона ✅
Стоит уточнить, что имеется в виду под некорректной

2023-03-05 20:21 UTC, george007361 commented on vdonate.md
> +- Номера нет в пуле обслуживаемых стран ✅
- Вывод на номер который есть в пуле ...
-  --"--- которого нет в пуле

2023-03-05 20:21 UTC, george007361 commented on vdonate.md
> +- Некорректная длина номера карты ✅
Уточнить какая именно длина

2023-03-08 11:18 UTC, george007361 approved these changes

2023-03-08 16:58 UTC, MrLeonardPak approved these changes

2023-03-08 17:08 UTC, merged