George Illarionov #fix_review_1
leonard-pak/technopark-qa-hw1 pull request #5
Opened 2023-03-12 16:26 UTC by george007361

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
> +   > Фактический: При большом количестве pop-up'ов, экран переполняется, верхние(более старые) уведомления становятся недостигаемыми
Фактический результат

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
> +    > Ожидание: Сообщение о том, что пользователи не найдены или список пользователей, в чьём имени содержатся спецсимволы.
Ожидаемый результат

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
> +    > Реальность: Выводится список всех юзеров.
И тут. И ниже ещё

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
>  13. Самбит пустого поля не изменяет никнейм ✅
Сабмит? Мб "сохранение"

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
>  13. Самбит пустого поля не изменяет никнейм ✅
Ну и так везде. Как то не сразу вникаешь, что именно хочешь сказать. Либо submit писать

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
> +   > Нажать на "Выбрать файл", в модальном окне указать "Все файлы *.*", выбрать файл, отличный от изображения (напр: doc.pdf), нажать на кнопку "Сохранить"
Лучше описать баг. Как вариант: При нажатии на ... и на ... появляется возможность выбрать любой тип файла для загрузки

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
> +   > Нажать на "Выбрать файл", в модальном окне указать выбрать файл-изображение (напр: ava.png) размером более 3 мб, нажать на кнопку "Сохранить"
Выше

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
>     >
Фактический результат?

2023-03-12 22:16 UTC, MrLeonardPak commented on vdonate.md
>  6. Ограничение на размер фото 3 Мб. Попробовать загрузить более тяжелое фото ❌
Ограничение на загрузку размер фото 3 Мб. (Второе предложение лишнее)

2023-03-12 23:57 UTC, themilchenko requested changes
Тавтология

2023-03-12 23:57 UTC, themilchenko commented on vdonate.md
>  3. При нажатии на крестик в pop-up'е, pop-up пропадает ✅
Тавтология.

2023-03-13 19:43 UTC, MrLeonardPak approved these changes

2023-03-13 19:59 UTC, themilchenko approved these changes

2023-03-13 20:04 UTC, zeronethunter approved these changes

2023-03-13 22:13 UTC, merged